name: Copy Secrets from oppie-thunder

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm copying secrets'
        required: true
        default: 'no'

jobs:
  copy-secrets:
    if: ${{ github.event.inputs.confirm == 'yes' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup GitHub CLI
        run: |
          echo "This workflow will help you copy secrets"
          echo "Since we can't read secret values, you need to:"
          echo ""
          echo "Option 1: Manual copy in GitHub UI"
          echo "1. Go to https://github.com/good-night-oppie/oppie-thunder/settings/secrets/actions"
          echo "2. Click on each secret to view"
          echo "3. Go to https://github.com/good-night-oppie/oppie-autonav/settings/secrets/actions"
          echo "4. Add each secret with the same name and value"
          echo ""
          echo "Option 2: Use GitHub's secret copying feature"
          echo "1. Go to Organization settings"
          echo "2. Set organization-level secrets"
          echo "3. Make them available to both repositories"
          echo ""
          echo "Required secrets:"
          echo "- CLAUDE_ACCESS_TOKEN"
          echo "- CLAUDE_CODE_OAUTH_TOKEN"  
          echo "- CLAUDE_EXPIRES_AT"
          echo "- CLAUDE_REFRESH_TOKEN"
          echo "- SECRETS_ADMIN_PAT (optional)"
      
      - name: Verify Secrets After Copy
        run: |
          echo "Checking if secrets are set..."
          
          SECRETS=(
            "CLAUDE_ACCESS_TOKEN"
            "CLAUDE_CODE_OAUTH_TOKEN"
            "CLAUDE_EXPIRES_AT"
            "CLAUDE_REFRESH_TOKEN"
          )
          
          for SECRET in "${SECRETS[@]}"; do
            if [ -n "${{ secrets[SECRET] }}" ]; then
              echo "✅ $SECRET is configured"
            else
              echo "❌ $SECRET is NOT configured"
            fi
          done